name: vita-android-build-alternative

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: v12.6_prev)'
        required: false
        default: 'v12.6_prev'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx6G
      VCPKG_ROOT: /usr/local/share/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
 
      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-${{ hashFiles('android/**.java') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-
            ${{ runner.os }}-gradle-

      - name: Set up build environment
        run: |
          sudo apt-get install -y ninja-build
          vcpkg install boost-system:arm64-android boost-filesystem:arm64-android boost-program-options:arm64-android boost-icl:arm64-android boost-variant:arm64-android openssl:arm64-android zlib:arm64-android

      - name: Decode Keystore
        env:
          KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
        run: echo $KEYSTORE_ENCODED | base64 --decode > "/home/runner/keystore.jks"

      - name: Gradle build
        env:
          SIGNING_STORE_PATH: "/home/runner/keystore.jks"
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          mkdir android/assets/data
          cp -r data/image android/assets/data/image
          cp -r lang android/assets
          cp -r vita3k/shaders-builtin android/assets
          export JAVA_HOME=$(echo $JAVA_HOME_17_X64)
          ./gradlew --stacktrace --info --configuration-cache --build-cache --parallel --configure-on-demand assembleRelease

      - name: Compute git short sha
        shell: bash
        run: echo "git_short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
    - name: Release Vita (Vita-Android)
      uses: softprops/action-gh-release@v2
      with:
        name: Vita ${{ steps.version.outputs.date }}
        tag_name: Vita
        files: ${{ github.workspace }}/vita-android-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release Vita ${{ steps.version.outputs.date }}
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.version.outputs.date }}
        tag_name: ${{ steps.version.outputs.date }}
        files: ${{ github.workspace }}/vita-android-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk
