name: vita-android-build-alternative

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: v12.6_prev)'
        required: false
        default: 'v12.6_prev'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx6G
      VCPKG_ROOT: /usr/local/share/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

    - name: Download Vita source code
      run: |
        cd ${{ github.workspace }}
        git clone --branch ${{ github.event.inputs.branch || 'v12.6_prev' }} https://github.com/XDeathUserX/Vita-Android.git --recursive
        cd Vita-Android
        

    - id: version
      name: Get version
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        cd ${{ github.workspace }}/Vita-Android
        echo "hash=$(git log -1 --pretty=format:%H)" >> $GITHUB_OUTPUT
        echo "short_hash=$(git describe --always --long)" >> $GITHUB_OUTPUT
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-vita-android-${{ steps.version.outputs.hash }}
        restore-keys: |
            ${{ runner.os }}-vita-android-

   # - name: Prepare environment
   #   run: |
   #     sudo apt-get install -y ninja-build
   #       ln -s /usr/bin/ninja .
    - name: Build Android
      run: |
        cd ${{ github.workspace }}/Vita-Android/src/android/
        chmod +x ./gradlew
        ./gradlew "assembleRelease"
        # bash gradlew build
        mv $(find app/build/outputs/apk/release/ -type f | grep -E "\.apk$") ${{ github.workspace }}/vita-android-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release Vita (Vita-Android)
      uses: softprops/action-gh-release@v2
      with:
        name: Vita ${{ steps.version.outputs.date }}
        tag_name: Vita
        files: ${{ github.workspace }}/vita-android-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release Vita ${{ steps.version.outputs.date }}
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.version.outputs.date }}
        tag_name: ${{ steps.version.outputs.date }}
        files: ${{ github.workspace }}/vita-android-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk
