name: Update submodules
on:
  schedule: [cron: 0 6 * * 0]
  workflow_dispatch:
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --no-recommend-shallow
    - name: Update submodules
      run: |
        if git commit -S -am"Update submodules (automated)

        $(git submodule -q foreach '

          # tag closest behind origin/HEAD
          tag="$(git describe --tags --abbrev=0 origin/HEAD)"

          # alternate method 1: latest release
          # tag="$(gh api repos/{owner}/{repo}/releases/latest -q .tag_name)"

          # alternate method 2: newest tag by date:
          # tag="$(git tag --sort=-creatordate | head -n1)"

          cur="$(git describe --tags)"
          if [ "$cur" != "$tag" ] && printf "%s\n%s" "$cur" "$tag" | sort -VC
          then
            git switch -dq -- "$tag"
            printf "%s\n" "$name: $cur -> $tag"
          fi'
        )"; then
          git show --raw
          git push
        fi
